blog with blueprint/home/routes.py
import pymysql
from db_config import mysql
from flask import Blueprint,render_template,url_for
home = Blueprint('home',__name__,template_folder='templates')

@home.route("/")
def index():
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT posts.id, posts.title, posts.content, posts.user_id, users.email FROM posts INNER JOIN users ON posts.user_id = users.id")
        rows = cursor.fetchall()
        return render_template("home/index.html", rows=rows)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()
    # return render_template("home/index.html")

blog with blueprint/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href={{url_for('static',filename='css/style.css')}}>
    <script src="{{url_for('static',filename='javascripts/jquery.js')}}"></script>
    <script src="{{url_for('static',filename='javascripts/validation.js')}}"></script>
</head>

<body class="body">
    <div id="sidebar" class="col-4">
        <div class="blog">
            <h4><a href="{{url_for('home.index')}}">SAMPLE BLOG</a></h4>
        </div>
        <div class="list">
            <ul>
                {% if session['loggedin']%}
                <li><a href="/new">Create New Post</a></li>
                <li><a href="{{url_for('users.profile',id=session['id'])}}">My Profile</a></li>
                <li><a href="/logout">Logout</a></li>
                {% else %}
                <li><a href="/login">Login</a></li>
                <li><a href="/signup">SignUp</a></li>
                {% endif %}
                <li><a href="/all_users">Users</a></li>
            </ul>
        </div>
        <div class="session">
            {% if session['loggedin']%}
            <a href="{{url_for('users.profile',id=session['id'])}}">
                <p>{{session['uname'].split('@')[0]}}</p>
            </a>
            {%endif%}
        </div>
    </div>
    <div id="content-div" class="col-12">
        {% block content %}

        {% endblock content %}
    </div>
</body>

</html>