blog with blueprint/users/routes.py
import pymysql
from db_config import mysql
from flask import Blueprint,render_template,url_for
from flask import flash, request, redirect, session
from werkzeug.security import generate_password_hash, check_password_hash



users = Blueprint('users',__name__,template_folder="templates")

@users.route('/all_users')
def all_users():
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute ("SELECT users.id, users.email, count(posts.id) AS no_of_posts, users.created_at From users LEFT JOIN posts ON users.id = posts.user_id GROUP BY users.id ORDER BY 4 DESC")
        users = cursor.fetchall()
        return render_template("users/users.html",users = users)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

@users.route('/view_user/<int:id>')
def view_user(id):
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT posts.id, posts.title, posts.content, count(comments.id) AS no_of_comments, posts.created_at, posts.updated_at FROM posts LEFT JOIN comments ON posts.id = comments.post_id WHERE posts.user_id = %s GROUP BY posts.id",id)
        user_posts = cursor.fetchall()
        cursor.execute("SELECT * from users WHERE id = %s", id)
        user = cursor.fetchone()
        return render_template("users/view_user.html",user_posts = user_posts,user = user)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

@users.route('/profile/<int:id>')
def profile(id):
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT * FROM users WHERE id = %s",id)
        user_profile = cursor.fetchone()
        cursor.execute("SELECT posts.id, posts.title, posts.content, count( comments.id ) AS no_of_comments, posts.created_at, posts.updated_at FROM posts LEFT JOIN comments ON posts.id = comments.post_id WHERE posts.user_id = %s GROUP BY posts.id",id)
        user_posts = cursor.fetchall()
        cursor.execute("SELECT comments.id, comments.name, comments.comment, posts.id as post_id, posts.title, comments.created_at FROM comments LEFT JOIN posts ON posts.id = comments.post_id WHERE comments.user_id = %s",id)
        user_comments = cursor.fetchall()
        cursor.execute("SELECT count(id) as no_of_posts FROM posts WHERE user_id = %s",id)
        user_no_posts = cursor.fetchone()
        cursor.execute("SELECT count(id) as no_of_comments FROM comments WHERE user_id = %s",id)
        user_no_comments = cursor.fetchone()
        return render_template("users/profile.html",user_posts = user_posts,user_profile = user_profile,user_comments = user_comments,user_no_posts = user_no_posts,user_no_comments=user_no_comments)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()
    return render_template('profile.html')

@users.route('/change_profile/<int:id>')    
def change_profile(id):
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT * FROM users WHERE id = %s",id)
        user_details = cursor.fetchone()
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()        
    return render_template('users/change_profile.html',user_details = user_details)

@users.route('/update_profile/<int:id>',methods=['POST'])
def update_profile(id):
    conn = None
    cursor = None
    if (
        request.method == "POST"
        and "email" in request.form
        and "current_password" in request.form
    ):
        _email = request.form["email"]
        _new_password = request.form["new_password"]
        _current_password = request.form['current_password']
        _hashed_current_password = generate_password_hash(_current_password)
        _hashed_new_password = generate_password_hash(_new_password)
        sql = "SELECT * FROM users WHERE id = %s"
        data = (id)
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute(sql,data)
        account = cursor.fetchone()
        if check_password_hash(account['password'],_current_password):
            if account:
                if _new_password != '':
                    try:
                        sql = "UPDATE users SET email = %s, password = %s where id = %s"
                        data = (_email, _hashed_new_password,id)
                        conn = mysql.connect()
                        cursor = conn.cursor()
                        cursor.execute(sql, data)
                        conn.commit()
                        sql = "SELECT * FROM users WHERE id = %s"
                        data = (id)
                        cursor.execute(sql,data)
                        account = cursor.fetchone()
                        session["loggedin"] = True
                        session["id"] = account[0]
                        session["uname"] = account[1]
                        return redirect(url_for('users.profile',id=id))
                    except Exception as e:
                        print(e)
                        return render_template("users/change_profile.html",user_details = account,error="Email already Exists")
                    finally:
                        conn.close()
                        cursor.close()
                else:
                    try:
                        sql = "UPDATE users SET email = %s, password = %s where id = %s"
                        data = (_email, _hashed_current_password,id)
                        conn = mysql.connect()
                        cursor = conn.cursor()
                        cursor.execute(sql, data)
                        conn.commit()
                        sql = "SELECT * FROM users WHERE id = %s"
                        data = (id)
                        cursor.execute(sql,data)
                        account = cursor.fetchone()
                        session["loggedin"] = True
                        session["id"] = account[0]
                        session["uname"] = account[1]
                    except Exception as e:
                        print(e)
                        return render_template("users/change_profile.html",user_details = account,error="Email already Exists")
                    finally:
                        conn.close()
                        cursor.close()

        else:
            error = "Incorrect current password!"
            return render_template('users/change_profile.html',user_details = account,error = error)
    return redirect(url_for('profile',id=id))


@users.route('/delete_profile/<int:id>')
def delete_profile(id):
    conn = None
    cursor = None
    try:
            sql = "SELECT * FROM users WHERE id = %s"
            data = (id)
            conn = mysql.connect()
            cursor = conn.cursor(pymysql.cursors.DictCursor)
            cursor.execute(sql,data)
            account = cursor.fetchone()
            if account:
                sql = "DELETE FROM comments WHERE user_id = %s"
                data = (id)
                cursor.execute(sql,data)
                conn.commit()
                sql = "DELETE FROM posts WHERE user_id = %s"
                data = (id)
                cursor.execute(sql,data)
                conn.commit()
                sql = "DELETE FROM users WHERE id = %s"
                data = (id)
                cursor.execute(sql,data)
                conn.commit()
                session.pop('loggedin', None)
                session.pop('id', None)
                session.pop('uname', None)
                return redirect(url_for('home.index',success = "Profile deleted Successfully"))
    except Exception as e:
        print(e)
    finally:
        conn.close()
        cursor.close()

blog with blueprint/users/templates/users/change_profile.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% if error|length > 0 %}
    <div class="error">
        <div class="closebtn" onclick="this.parentElement.style.display='none';">&times;</div>
        <h4>{{error}}</h4>
    </div>
    {% endif %}
    <div class="post-div">
        <h4 align="center">Change Profile</h4>
        <form action="{{url_for('users.update_profile',id=user_details['id'])}}" method="post">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" id="email" placeholder="Email"
                    value="{{user_details['email']}}">
            </div>
            <div class="form-group">
                <label for="new_password">New Password</label>
                <input type="text" class="form-control" name="new_password" id="new_password"
                    placeholder="New Password">
            </div>
            <div class="form-group">
                <label for="confirm_password">Confirm Password</label>
                <input type="text" class="form-control" name="confirm_password" id="confirm_password"
                    placeholder="Confirm Password">
            </div>
            <div class="form-group">
                <label for="currrent_password">Current Password</label>
                <input type="text" class="form-control" name="current_password" id="current_password"
                    placeholder="Current Password">
                <p>Enter Current Password to save changes :)</p>
            </div>
            <div class="form-group">
                <input type="submit" value="save changes" class="btn btn-primary sub">
            </div>
            <div class="delete-profile">
                <p>Unhappy :(</p>
                <p><a href="{{url_for('users.delete_profile',id=user_details['id'])}}"
                        onclick="return confirm('Are you sure ?')">Delete</a> your Account.</a></p>
            </div>
        </form>
    </div>

</div>

{% endblock content %}H

blog with blueprint/users/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>{{user_profile.email.split('@')[0]}}'s Profile</h1>
    <hr>
    <div class="profile-details-header">
        <div class="profile-details">
            <p class="email">Email :: <strong>{{user_profile.email}}</strong></p>
            <p class="created-on">Created On :: <strong>{{user_profile.created_at}}</strong></p>
            <p class="updated-on">Updated On :: <strong>{{user_profile.updated_at}}</strong></p>
        </div>
        <div class="change-profile">
            <strong>
                <p>Change profile settings</p>
            </strong>
            <a href="{{url_for('users.change_profile',id=user_profile['id'])}}">Change</a>
        </div>
    </div>
    <hr>
    <div class="profile-content">
        <div class="profile-posts">
            <div class="profile-posts-head">
                <p>No. of Posts <span>{{user_no_posts.no_of_posts}}</span>
                </p>
            </div>
            {% if user_posts|length > 0 %}
            {% for user_post in user_posts %}
            <div class="profile-posts-row">
                <a href="{{url_for('posts.show',id=user_post['id'])}}">
                    <h5 class="user-post-title">{{user_post.title}}</h5>
                </a>
                <p>Created on :: {{user_post.created_at}}</p>
                <p>Updated on :: {{user_post.updated_at}}</p>
                <p>No. of Comments :: {{user_post.no_of_comments}}</p>
            </div>
            <hr>
            {% endfor %}
            {% else %}
            <div class="profile-posts-row">
                <h5>No posts yet :( </h5>
            </div>
            {% endif %}
        </div>
        <div class="profile-comments">
            <div class="profile-comments-head">
                <p>No. of Comments <span>{{user_no_comments.no_of_comments}}</span>
                </p>
            </div>
            {% if user_comments|length > 0 %}
            {% for user_comment in user_comments %}
            <div class="profile-comments-row">
                <a href="{{url_for('posts.show',id=user_comment['post_id'])}}">
                    <h5 class="user-comment">{{user_comment.comment}}</h5>
                </a>
                <p>On post :: {{user_comment.title}}</p>
                <p>Commented on :: {{user_comment.created_at}}</p>
            </div>
            <hr>
            {% endfor %}
            {% else %}
            <div class="profile-comments-row">
                <h5>No Comments yet :(</h5>
            </div>
            {% endif %}
        </div>
    </div>
    <hr>
</div>

{% endblock content%}

blog with blueprint/users/templates/users/users.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>All Users</h1>
    <hr>
    {% for user in users %}
    <div class="user-row">
        <div class="user-head">
            <a href="{{url_for('users.view_user',id=user['id'])}}">
                <h3>{{user.email.split('@')[0]}}</h3>
            </a>
        </div>
        <div class="user-foot">
            <div class="user-at">
                <div class="create">Created at :: <strong>{{user.created_at}}</strong></div>
            </div>
            <div class="user-posts-count">
                <div class="no-posts">No. of Posts :: <strong>{{user.no_of_posts}}</strong></div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock content %}

blog with blueprint/users/templates/users/view_user.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>{{user.email.split('@')[0]}}'s Posts</h1>
    <hr>
    {% if user_posts|length > 0 %}
    {% for user_post in user_posts %}
    <div class="user-post">
        <div class="post-head">
            <h4>{{user_post.title}}</h4>
        </div>
        <div class="post-body">
            <p class="show-some">{{user_post.content}}</p>
            <a href="{{url_for('posts.show',id=user_post['id'])}}">Read more ... </a>
        </div>
        <hr>
        <div class="post-foot">
            <div class="create_at">created at :: {{user_post.created_at}}</div>
            <div class="update_at">updated at :: {{user_post.updated_at}}</div>
            <div class="no-comments">No. of comments :: {{user_post.no_of_comments}}</div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h4>No Posts Yet :(</h4>
    {% endif %}

    {% endblock content%}